### ISSUE TITLE
Pyseg fails when capturing disprese exceptions.

### ISSUE THREAD

**Issue by pconesa** [anmartinezs/pyseg_system#16]
Since pexception commented, all the "raise exceptions .." fails.

https://github.com/anmartinezs/pyseg_system/blob/536581c5773a7ef0f82ac45db363a6970e011137/code/pyseg/disperse_io/handler.py#L18

**Comment by anmartinezs** [comment]
Thanks to notice, actually if "raise pexceptions .." is reached something should be wrong, so an exception will be raised anyway, unless you want to catch and handle this pexception especifically.

**Comment by pconesa** [comment]
Yes I agree, but the raised exception can inform about the error, and not cause a second exception. As it is now you are loosing the chance to raise an exception, maybe suggesting what to do, point to a URL or something that may help the user to address the problem

**Comment by anmartinezs** [comment]
This issue has been fixed in the latest released tag v2.0.3.
