### ISSUE TITLE
Steps to run python3 Version

### ISSUE THREAD

**Issue by horizenight** [anmartinezs/pyseg_system#21]
there are many package errors while installing the python3 version , namely graph-tool module not found and it not being available to install , also a clear script for running and installing conda packages will help ! 

Kindly guide how to setup it for python3

**Comment by anmartinezs** [comment]
Yes, we have forgotten to update the installers for python 3. Now you have the installeres tested for Python 3.9 and Ubuntu 20.04 on master and released as tag v2.0.5.
