### ISSUE TITLE
Specific way to execute the script ?

### ISSUE THREAD

**Issue by horizenight** [anmartinezs/pyseg_system#22]
While following the synth_sumb tutorial encountered with the following error 
```
(pyseg) user@pikachu:~/Desktop/kshitij$ python pyseg_system/code/tutorials/synth_sumb/pre/gen_microsomes.py 
Traceback (most recent call last):
  File "/home/user/Desktop/kshitij/pyseg_system/code/tutorials/synth_sumb/pre/gen_microsomes.py", line 34, in <module>
    from pyorg import disperse_io, sub, spatial
ModuleNotFoundError: No module named 'pyorg'

```

**Comment by anmartinezs** [comment]
It looks like your PYTHONPATH environment variable is not set properly, did you execute sys/set_bashrc_env.sh script after PySeg installation? this script sets the required environment variables in your .bashrc file.

**Comment by horizenight** [comment]
yes I followed all the installation instruction and currently trying to execute 'synth_sumb' tutorial . 
```
FileNotFoundError: [Errno 2] No such file or directory: '../../../../data/tutorials/synth_sumb/models/4uqj_r2.62_90_nostd.mrc'
```
I had also run the ./clean_out_data.sh script . But cant see this file under the data folder .

**Comment by anmartinezs** [comment]
It is asking for the input densities to include in your synthetic datasets. I've already uploaded them to GitHub **/data/tutorials/synth_sumb/models** in the master branch.
